
package download

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"syscall"
	"time"
	"os/signal"
	"github.com/MakeNowJust/heredoc"
	"github.com/cli/cli/v2/internal/safepaths"
	"github.com/cli/cli/v2/pkg/cmd/run/shared"
	"github.com/cli/cli/v2/pkg/cmdutil"
	"github.com/cli/cli/v2/pkg/iostreams"
	"github.com/cli/cli/v2/pkg/set"
	"github.com/spf13/cobra"
)

// debugEnabled returns true if the debug flag is set in DownloadOptions.
var debugEnabledFunc func() bool = func() bool { return false }

func setDebugEnabledFunc(f func() bool) {
    debugEnabledFunc = f
}

func debugLogf(format string, args ...interface{}) {
    if debugEnabledFunc() {
        fmt.Fprintf(os.Stderr, "[gh run download debug] "+format+"\n", args...)
    }
}

type DownloadOptions struct {
	IO       *iostreams.IOStreams
	Platform platform
	Prompter iprompter
	DoPrompt       bool
	RunID          string
	DestinationDir string
	Names          []string
	FilePatterns   []string
	Debug          bool
	Concurrency    int
}

type platform interface {
	List(runID string) ([]shared.Artifact, error)
	Download(url string, dir safepaths.Absolute, progress func(downloaded, total int64)) error
}

type iprompter interface {
	MultiSelect(string, []string, []string) ([]int, error)
}

func NewCmdDownload(f *cmdutil.Factory, runF func(*DownloadOptions) error) *cobra.Command {
	opts := &DownloadOptions{
		IO:         f.IOStreams,
		Prompter:   f.Prompter,
		Concurrency: 4,
	}

	cmd := &cobra.Command{
		Use:   "download [<run-id>]",
		Short: "Download artifacts generated by a workflow run",
		Long: heredoc.Docf(`
			Download artifacts generated by a GitHub Actions workflow run.

			The contents of each artifact will be extracted under separate directories based on
			the artifact name. If only a single artifact is specified, it will be extracted into
			the current directory.

			By default, this command downloads the latest artifact created and uploaded through
			GitHub Actions. Because workflows can delete or overwrite artifacts, %[1]s<run-id>%[1]s
			must be used to select an artifact from a specific workflow run.
		`, "`"),
		Args: cobra.MaximumNArgs(1),
		Example: heredoc.Doc(`
			# Download all artifacts generated by a workflow run
			$ gh run download <run-id>

			# Download a specific artifact within a run
			$ gh run download <run-id> -n <name>

			# Download specific artifacts across all runs in a repository
			$ gh run download -n <name1> -n <name2>

			# Select artifacts to download interactively
			$ gh run download
		`),
		   RunE: func(cmd *cobra.Command, args []string) error {
			   if len(args) > 0 {
				   opts.RunID = args[0]
			   } else if len(opts.Names) == 0 &&
				   len(opts.FilePatterns) == 0 &&
				   opts.IO.CanPrompt() {
				   opts.DoPrompt = true
			   }
			   // support `-R, --repo` override
			   baseRepo, err := f.BaseRepo()
			   if err != nil {
				   return err
			   }
			   httpClient, err := f.HttpClient()
			   if err != nil {
				   return err
			   }
			   opts.Platform = &apiPlatform{
				   client: httpClient,
				   repo:   baseRepo,
			   }
			   setDebugEnabledFunc(func() bool { return opts.Debug })
			   if runF != nil {
				   return runF(opts)
			   }
			   return runDownload(opts)
		   },
	   }

	cmd.Flags().StringVarP(&opts.DestinationDir, "dir", "D", ".", "The directory to download artifacts into")
	cmd.Flags().StringArrayVarP(&opts.Names, "name", "n", nil, "Download artifacts that match any of the given names")
	cmd.Flags().StringArrayVarP(&opts.FilePatterns, "pattern", "p", nil, "Download artifacts that match a glob pattern")
	cmd.Flags().BoolVar(&opts.Debug, "debug", false, "Enable debug logging for download operations")
	cmd.Flags().IntVar(&opts.Concurrency, "concurrency", 4, "Number of concurrent downloads for large artifacts")

	return cmd
}

func runDownload(opts *DownloadOptions) error {
		setDebugEnabledFunc(func() bool { return opts.Debug })
	debugLogf("runDownload: started")

	   // Setup signal handling for cleanup
	   sigCh := make(chan os.Signal, 1)
	   doneCh := make(chan struct{})
	   signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	   defer signal.Stop(sigCh)
	   defer close(doneCh)

	   go func() {
		   select {
		   case <-sigCh:
			   opts.IO.StopProgressIndicator()
			   os.Exit(1)
		   case <-doneCh:
			   return
		   }
	   }()

	   opts.IO.StartProgressIndicator()
	   artifacts, err := opts.Platform.List(opts.RunID)
	   opts.IO.StopProgressIndicator()
	   if err != nil {
		   return fmt.Errorf("error fetching artifacts: %w", err)
	   }

	numValidArtifacts := 0
	for _, a := range artifacts {
		if a.Expired {
			continue
		}
		numValidArtifacts++
	}
	if numValidArtifacts == 0 {
		return errors.New("no valid artifacts found to download")
	}

	wantPatterns := opts.FilePatterns
	wantNames := opts.Names
	if opts.DoPrompt {
		artifactNames := set.NewStringSet()
		for _, a := range artifacts {
			if !a.Expired {
				artifactNames.Add(a.Name)
			}
		}
		options := artifactNames.ToSlice()
		if len(options) > 10 {
			options = options[:10]
		}
		var selected []int
		if selected, err = opts.Prompter.MultiSelect("Select artifacts to download:", nil, options); err != nil {
			return err
		}
		wantNames = []string{}
		for _, x := range selected {
			wantNames = append(wantNames, options[x])
		}
		if len(wantNames) == 0 {
			return errors.New("no artifacts selected")
		}
	}

	opts.IO.StartProgressIndicator()
	defer opts.IO.StopProgressIndicator()

	// track downloaded artifacts and avoid re-downloading any of the same name, isolate if multiple artifacts
	downloaded := set.NewStringSet()
	isolateArtifacts := isolateArtifacts(wantNames, wantPatterns)

	absoluteDestinationDir, err := safepaths.ParseAbsolute(opts.DestinationDir)
	if err != nil {
		return fmt.Errorf("error parsing destination directory: %w", err)
	}

	for _, a := range artifacts {
		if a.Expired {
			continue
		}
		if downloaded.Contains(a.Name) {
			continue
		}
		if len(wantNames) > 0 || len(wantPatterns) > 0 {
			if !matchAnyName(wantNames, a.Name) && !matchAnyPattern(wantPatterns, a.Name) {
				continue
			}
		}

		destDir := absoluteDestinationDir
		if isolateArtifacts {
			destDir, err = absoluteDestinationDir.Join(a.Name)
			if err != nil {
				var pathTraversalError safepaths.PathTraversalError
				if errors.As(err, &pathTraversalError) {
					return fmt.Errorf("error downloading %s: would result in path traversal", a.Name)
				}
				return err
			}
		}

			   debugLogf("Starting download for artifact: %s", a.Name)
		progressFn := buildProgressFn(opts, a.Name)
		if p, ok := opts.Platform.(interface{ DownloadWithConcurrency(string, safepaths.Absolute, func(downloaded, total int64), int) error }); ok {
			err = p.DownloadWithConcurrency(a.DownloadURL, destDir, progressFn, opts.Concurrency)
		} else {
			err = opts.Platform.Download(a.DownloadURL, destDir, progressFn)
		}
		if err != nil {
					   debugLogf("Download error for %s: %v", a.Name, err)
			return fmt.Errorf("error downloading %s: %w", a.Name, err)
		}
			   debugLogf("Download complete for artifact: %s", a.Name)
		downloaded.Add(a.Name)
	}

	if downloaded.Len() == 0 {
		return errors.New("no artifact matches any of the names or patterns provided")
	}

	return nil
}

func isolateArtifacts(wantNames []string, wantPatterns []string) bool {
	if len(wantPatterns) > 0 {
		// Patterns can match multiple artifacts
		return true
	}

	if len(wantNames) == 0 {
		// All artifacts wanted regardless what they are named
		return true
	}

	if len(wantNames) > 1 {
		// Multiple, specific artifacts wanted
		return true
	}

	return false
}

func matchAnyName(names []string, name string) bool {
	for _, n := range names {
		if name == n {
			return true
		}
	}
	return false
}

func matchAnyPattern(patterns []string, name string) bool {
	for _, p := range patterns {
		if isMatch, err := filepath.Match(p, name); err == nil && isMatch {
			return true
		}
	}
	return false
}

// buildProgressFn returns a progress callback that updates the spinner label with the artifact
// name, download progress, and download speed.
// - Progress percentage is updated responsively (0.1% increments when the total size is known).
// - Download speeds are computed less frequently and smoothed for stability.
// When the spinner is not active (e.g., non-TTY or spinner disabled), the callback is a no-op.
func buildProgressFn(opts *DownloadOptions, artifactName string) func(downloaded, total int64) {
	if opts.IO.GetSpinnerDisabled() {
		return nil
	}

	start := time.Now()

	var (
		lastReport     time.Time
		lastN          int64
		smoothedCurBps float64
	)

	const (
		speedInterval = 500 * time.Millisecond
		alpha         = 0.25 // EMA smoothing factor; higher = more responsive, lower = smoother
	)

	return func(downloaded, total int64) {
		debugLogf("progressFn: artifact=%s downloaded=%d total=%d", artifactName, downloaded, total)
		now := time.Now()

		// Prevent spinner updates after completion
		if total > 0 && downloaded >= total {
					   debugLogf("progressFn: artifact=%s completed", artifactName)
			return
		}

		// Update speed estimates at a slower cadence for stability, but always on completion.
		done := total > 0 && downloaded >= total
		if lastReport.IsZero() || now.Sub(lastReport) >= speedInterval || done {
			// Average B/s
			elapsed := now.Sub(start).Seconds()
			avgBps := 0.0
			if elapsed > 0 {
				avgBps = float64(downloaded) / elapsed
			}

			// Current (windowed) B/s, smoothed via EMA
			dt := now.Sub(lastReport).Seconds()
			if lastReport.IsZero() {
				dt = 0
			}
			if dt > 0 {
				sample := float64(downloaded-lastN) / dt
				if smoothedCurBps == 0 {
					smoothedCurBps = sample
				} else {
					smoothedCurBps = alpha*sample + (1-alpha)*smoothedCurBps
				}
			}

			lastReport = now
			lastN = downloaded

			// Build label
			var label string
			curStr := fmt.Sprintf("%s/s", formatBytes(int64(smoothedCurBps)))
			avgStr := fmt.Sprintf("%s/s", formatBytes(int64(avgBps)))

			if total > 0 {
				pct10 := (downloaded * 1000) / total
				if pct10 > 1000 {
					pct10 = 1000
				}
				label = fmt.Sprintf("Downloading %s: %.1f%% (%s cur, %s avg)", artifactName, float64(pct10)/10.0, curStr, avgStr)
			} else {
				label = fmt.Sprintf("Downloading %s: %s (%s cur, %s avg)", artifactName, formatBytes(downloaded), curStr, avgStr)
			}

			opts.IO.StartProgressIndicatorWithLabel(label)
		}
	}
}

// formatBytes formats a byte count as a human-readable string.
func formatBytes(n int64) string {
	switch {
	case n < 1024:
		return fmt.Sprintf("%d B", n)
	case n < 1024*1024:
		return fmt.Sprintf("%.1f KB", float64(n)/1024)
	default:
		return fmt.Sprintf("%.1f MB", float64(n)/(1024*1024))
	}
}
